on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 1"

name: Anti the Facists

jobs:
  build_and_test:
    name: Anti the Facists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: ./target
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo run -r -- -ic ${{ secrets.AFI_COOKIE }}
