on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 1"

name: CI

jobs:
  build_and_test:
    name: Anti the Facists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo run -- -ic ${{ secrets.AFI_COOKIE }}
